{{- if .Values.sshPrivateKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mkdocs-helm.fullname" . }}-ssh
type: kubernetes.io/ssh-auth
data:
  # the data is abbreviated in this example
  ssh-privatekey: |
    {{ .Values.sshPrivateKey | b64enc }}
{{- end -}}
